### ISSUE TITLE
Question regarding StieVariable.cpp

### ISSUE THREAD

**Issue by GYengera** [whuang08/ROPTLIB#1]
Hello @whuang08,

I have written an optimization problem in which I am using a variable on the stacked Stiefel manifold (St(d,p)^n, i.e R_{p x nd}) such that **p > d**. When the function StieVariable::RandInManifold() is called to initialize points on the Stiefel manifold St(p,d), an error occurs in the dorgqr_() function due to the manner in which arguments are passed to it. A good explanation for this problem is given at the link : http://scicomp.stackexchange.com/questions/7892/lapack-dorgqr-qr-decomposition-matrix-m-times-n-with-mn

Do you think modifying the RandInManifold() function to work in both cases (m >= n and m < n) for a m x n matrix be a good idea?

**Comment by whuang08** [comment]
Thank you for being interested in ROPTLIB. 
In current version of ROPTLIB, Stiefel manifold is represented by St(p, n) = \{ X \in R^{n \times p} | X^T X = I\}, where n >= p. The matrix is stored in column major order.
You can viewed it as a St(n, p) = \{ X \in R^{p \times n} | X X^T = I\}, where n >= p. and the matrix is stored in row major order.
The current approach should be sufficient for all the problems on Stiefel manifolds. Let me know if you have any specific needs.

**Comment by GYengera** [comment]
Thank you for the reply. I understand your point. I think my confusion is occurring when working with the ProductElement class. I am trying to stack St(d,p) n times to create a matrix X \in R^{p \times dn}. Is it possible to treat a ProductElement as one large matrix, or do I need to extract each element from within it?

**Comment by whuang08** [comment]
It is possible. Actually, the current version already organize the product of manifolds such that the components are stored in consecutive memory. In other words, for manifolds St(d, p)^n, p > d, the point on this product manifold is stored as a p by dn matrix:
[X_1, X_2, ... X_n], (column major).
Specifically, you could create a ProductElement by
	integer p = 3, d = 2, n = 10; // St(2, 3)^10
	integer numofmanis = 1; // one kind of manifold St(2, 3)
	integer numofmani1 = 10; // this kind of manifold has power 10

	StieVariable StieX(p, d);
	ProductElement ProdX(numofmanis, &StieX, numofmani1);
	ProdX.RandInManifold(); // randomly generate a point on this manifold.

        //Two ways to obtain data in ProdX:
        //(1): Xptr is a pointer to the large matrix [X_1, X_2, ... X_n](column major).
	const double *Xptr = ProdX.ObtainReadData();  // or ObtainWriteEntireData, ObtainWritePartialData
        //(2): Xiptr is a pointer to the i-th component X_i
        const double *Xiptr = ProdX.GetElement(i)->ObtainReadData();

I think what you need is the first approach. The second approach is useful if there exist different kinds of manifolds.

**Comment by GYengera** [comment]
I have been able to successfully run my optimization problem. At first I was under the mistaken impression that the matrices were being stored in row major order, but I had still declared the pointer to the product element correctly. The main mistake I was making was in initializing a particular matrix, which I have now solved. Thanks for your help.
