### ISSUE TITLE
Memory storage for product of product manifolds

### ISSUE THREAD

**Issue by jbriales** [whuang08/ROPTLIB#3]
Hi @whuang08,
I have a relatively simple question regarding the memory storage policy for product manifolds.
I already know from the documentation that the components in a product manifold are stored in consecutive memory. I would like to confirm if this is the same if we have product manifolds as the elements of the product manifold. To make clearer this question, let me pose an example where I have a collection of SE(d)=SO(d)xRe^d variables:

```
OrthGroup OrthMani(d);
Euclidean LinearMani(d);
ProductManifold CartanMani(2, OrthMani,1, LinearMani,1);
ProductManifold domain(1, CartanMani, n);

const double *Xptr = domain.ObtainReadData();
```

May I assume that using this construction, Xptr is a pointer to the large matrix [R_0, t_0, R_1, t_1, ..., R_{n-1}, t_{n-1}](column major)?

**Comment by whuang08** [comment]
I give an example that is probably what you want.

	integer d = 3;
	integer n = 2;
	/*This is used to generate a Manifold. You can use this manifold to compute operations on this manifold, such as retraction, vector transport....
	This is not used to generate a point on the manifold.*/
	OrthGroup OrthMani(d);
	Euclidean LinearMani(d);
	ProductManifold CartanMani(2, OrthMani, n, LinearMani, n); 

	/*This is used to generate a point on a manifold*/
	OrthGroupVariable OrthV(d);
	EucVariable EucV(d);
	ProductElement ProdX(2, &OrthV, n, &EucV, n); /*two kinds of manifolds. The number of each kind is n.*/
	ProdX.RandInManifold();  /*Randomly generate a point on this manifold*/

	ProdX.Print("A point on the product manifold:");

	std::cout << "output numbers in the consecutive memory:" << std::endl;
	const double *Xptr = ProdX.ObtainReadData();
	// The command 
	//      ForDebug::Print("Xptr:", Xptr, d * d * n + n * d);
	// is a short-cut for the following for-loop
	for (integer i = 0; i < d * d * n + d * n; i++) 
		std::cout << Xptr[i] << std::endl;

Note that generating a manifold is different from generating a point on a manifold. A manifold is not a container-class. Instead, it has operations on the manifold, such as retraction.

**Comment by jbriales** [comment]
Thanks!
You're absolutely right in the point vs. manifold aspect. Although actually my question referred specially to the *nesting of product manifolds*, as I'm interested in having the interleaved structure [R_0, t_0, R_1, t_1, ..., R_{n-1}, t_{n-1}] rather than [R_0, R_1, ..., R_{n-1}, t_0, t_1, ..., t_{n-1}]. So, if I define a point as
```
/*This is used to generate a point on a manifold*/
OrthGroupVariable OrthV(d);
EucVariable EucV(d);
// Generate product pair [R_i,t_i]
ProductElement InnerProdX(2, &OrthV, 1, &EucV, 1); /*two kinds of manifolds, one of each*/
// Repeat block above to get desired pattern [R_0, t_0, R_1, t_1, ..., R_{n-1}, t_{n-1}]
ProductElement OuterProdX(1, &InnerProdX, n); /*The pair above is repeated n times*/
OuterProdX.RandInManifold();  /*Randomly generate a point on this manifold*/
```
is it still the expected behavior to use consecutive memory storage in the order [R_0, t_0, R_1, t_1, ..., R_{n-1}, t_{n-1}]?

**Comment by whuang08** [comment]
Yes, you can use the method to produce the consecutive memory storage. The codes are given as follows:

	integer d = 3;
	integer n = 2;
	/*This is used to generate a Manifold. You can use this manifold to compute operations on this manifold, such as retraction, vector transport....
	This is not used to generate a point on the manifold.*/
	OrthGroup OrthMani(d);
	Euclidean LinearMani(d);
	ProductManifold CartanMani(2, OrthMani, 1, LinearMani, 1);
	ProductManifold ProdMani(1, CartanMani, n);
	/*This is used to generate a point on a manifold*/
	OrthGroupVariable OrthV(d);
	EucVariable EucV(d);
	ProductElement ProdX(2, &OrthV, 1, &EucV, 1); /*two kinds of manifolds. One for each.*/
	ProductElement OProdX(1, &ProdX, n);
	OProdX.RandInManifold();  /*Randomly generate a point on this manifold*/
	OProdX.Print("A point on the product manifold:");
	std::cout << "output numbers in the consecutive memory:" << std::endl;
	const double *Xptr = OProdX.ObtainReadData();
	// The command 
	//      ForDebug::Print("Xptr:", Xptr, d * d * n + n * d);
	// is a short-cut for the following for-loop
	for (integer i = 0; i < d * d * n + d * n; i++) 
		std::cout << Xptr[i] << std::endl;

The output of the above codes is:
=================Product data: A point on the product manifold:===========
=================Product data: number 0 manifold=========================
number 0 manifold , shared times:1, shared times address:000000000049BFB0
-1.8387007043e-01       -8.4245994662e-01       -5.0641192278e-01
9.6674448863e-01        -2.4815891639e-01       6.1824315020e-02
-1.7775514314e-01       -4.7820329416e-01       8.6007250772e-01
number 1 manifold , shared times:1, shared times address:000000000049BEB0
-4.1483667483e-01
1.4096215813e+00
3.7121341816e-01
=================Product data: number 1 manifold=========================
number 0 manifold , shared times:1, shared times address:000000000049BEF0
-5.1849076093e-01       8.5347526315e-01        5.2414750014e-02
-7.8121674454e-01       -4.4788755988e-01       -4.3485300017e-01
-3.4766036426e-01       -2.6641454332e-01       8.9897472836e-01
number 1 manifold , shared times:1, shared times address:000000000049BF30
-1.9057309577e+00
-1.7885029291e+00
9.1744900727e-01
output numbers in the consecutive memory:
-0.18387
0.966744
-0.177755
-0.84246
-0.248159
-0.478203
-0.506412
0.0618243
0.860073
-0.414837
1.40962
0.371213
-0.518491
-0.781217
-0.34766
0.853475
-0.447888
-0.266415
0.0524148
-0.434853
0.898975
-1.90573
-1.7885
0.917449

**Comment by jbriales** [comment]
Great! That definitely solves my question. Thanks a lot!
