### ISSUE TITLE
Preconditioner for RTR

### ISSUE THREAD

**Issue by jbriales** [whuang08/ROPTLIB#4]
Hi,
I was trying to find out: Is it possible to use preconditioning in the RTRNewton solver?
I tried looking at the manual and documentation, but it's not clear for me if this functionality is available or, if so, how to use it.

**Comment by whuang08** [comment]
Yes, it is possible. The function for preconditioning is 
void SolversTR::PreConditioner(Variable *x, Vector *eta, Vector *result)
in the file "SolversTR.cpp".
I think the easiest way is to modify this function. In this class, the domain manifold
and Problem are available as objects: (Defined in Solvers.h)
const Manifold *Mani;	/*The manifold on which the cost function is*/
const Problem *Prob;	/*The problem which defines the cost function, gradient and probably action of Hessian*/

**Comment by jbriales** [comment]
Thanks!
I wonder, would it be a good idea to (optionally) provide the preconditioner as a method in Problem, then calling this from SolversTR, just as it's done e.g. with `HessianEta`? This should allow easy customization for the preconditioner via the user-defined problem, making the approach similar to that in Manopt.
Let me know if this would be ok for you and I could provide a pull request with the changes.

**Comment by whuang08** [comment]
Yes, providing the preconditioner in Problem is a good idea. Thanks.

**Comment by whuang08** [comment]
I have updated ROPTLIB and the latest version in github allows users to define a preconditioner through its Problem class.
