### ISSUE TITLE
Header conflicts with Eigen

### ISSUE THREAD

**Issue by jbriales** [whuang08/ROPTLIB#5]
Hi again!
I'm having some weird header conflicts when combining ROPTLIB together with the Eigen library.
Somehow, it seems including the *f2c.h* header in *ROPTLIB/cwrapper/blas/f2c.h* drives to some conflict that makes compilation fail. This happens only if *f2c.h* is included before *Eigen*, but it is difficult to prevent this from happening when coding regularly in a project.
I'm attaching a minimal project where the conflict happens.
[testProject.zip](https://github.com/whuang08/ROPTLIB/files/1278705/testProject.zip)

Is it possible to modify somehow the inclusion of *f2c.h* so that it doesn't conflict with external projects such as Eigen?

Best,
- Jesus

**Comment by jlblancoc** [comment]
With all the pain in my eyes after watching the horrible coding practices inside `f2c.h` (in which century was *that* written?)... I have debugged and fixed this problem! ;-)

It all has to do with a couple of problems: 
* f2c `#define`s a lot of symbols, which create conflicts in any other code. We must `#undef`ine them all **after** including f2c. See code below. Hope it's easy to integrate into your projects.
* Eigen has another minor issue. See the comment before the Eigen include below. Please, feel free to submit a patch/bug report to Eigen to get this fixed (I don't have time to do it! :-) 

Cheers!

```cpp
// Eigen needs to be before f2c.h to avoid conflicts
#include "f2c.h"

#undef TRUE_
#undef FALSE_
#undef Extern
#undef VOID
#undef abs
#undef dabs
#undef min
#undef max
#undef dmin
#undef dmax
#undef bit_test
#undef bit_clear
#undef bit_set

// to modify in Eigen headers: 
// eigen\src/Core/GenericPacketMath.h(527) uses "real" and should 
// be "std::real". Idem for: "imag" => "std::imag"
#include "Eigen/Core"

```

**Comment by bbrrck** [comment]
Had the exact same problem (conflicting symbols from `f2c.h`) some time ago. My solution was simply to `#include` the ROPTLIB headers at the very end, after including everything else. As @jbriales pointed out, this might be difficult to control for larger projects.

**Comment by jbriales** [comment]
Thanks for all the comments!
After exploring the context where `f2c.h` is included in ROPTLIB, I made the following observations:
1. Most of the content in this file (that is, many potentially conflicting definitions) are not used (e.g. `abs(x)`). Could we remove all of these?
2. The actually necessary definitions are used (very locally) for wrapping Fortran functions (in the headers in *cwrappers/blas* and *cwrappers/lapack*). Some of these (e.g. `real`) are conflicting with `std` and `Eigen`, but can be safely renamed to avoid conflict (e.g. to `f2c_real`, as done [in this project](https://www-sop.inria.fr/galaad/software/synaps/f2c_8h-source.html)).

After these modifications my project compiles correctly and the ROPTLIB headers can be placed anywhere without incurring on compilation issues.

**Comment by whuang08** [comment]
Thank you for the helpful comments and the useful link and suggestions. I will update ROPTLIB correspondingly as soon as possible. If the contents (e.g. abs(x)) are not used, then I believe we can remove all of these.

**Comment by whuang08** [comment]
I just updated ROPTLIB and this problem should be resolved. Thank you for all the comments.
