### ISSUE TITLE
Dependency on FFTW

### ISSUE THREAD

**Issue by jbriales** [whuang08/ROPTLIB#6]
Hi!
I would like to point out that after the inclusion of FFTW in ROPTLIB, this has become a necessary dependency that may make the compilation fail if not installed.
For those who may have this issue, I wanted to share that in Ubuntu 14.04 (and I guess for more recent versions as well) you need to install:
`sudo apt-get install libfftw3-3 libfftw3-dev`
It is important to install the *-dev* package as well, otherwise the symbolic link *libfftw3.so* is not created.
You may want to indicate this in some kind of *dependencies* section in the README :)

Best,
- Jesus

**Comment by jlblancoc** [comment]
I think libfftw3-dev should be enough. The others are installed as a
dependency of the "-dev" package.
Please, give it a try if you want... The simpler the instructions to
users, the better ;-)

**Comment by whuang08** [comment]
Thank you very much. Below is the updated user manual.
[USER_MANUAL.pdf](https://github.com/whuang08/ROPTLIB/files/1290806/USER_MANUAL.pdf)
Information about compiling on various platforms is added in the user manual. After I finish the next released version, I will update the corresponding version on
https://www.math.fsu.edu/~whuang2/Indices/index_ROPTLIB.html
